=== phl-code-club/website/src/organizer.schema.json
{
  "$schema": "https://json-schema.org/draft-04/schema#",
  "title": "PHL Code Club Organizer",
  "description": "Requisite info for displaying the organizer page",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "title": {
      "type": "string"
    },
    "photo": {
      "type": "string"
    },
    "email": {
      "type": "string"
    },
    "emoticon": {
      "type": "string"
    },
    "bio": {
      "type": "string"
    },
    "dislikes": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "likes": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "links": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "required": [
          "url"
        ],
        "properties": {
          "icon": {
            "type": "string"
          },
          "url": {
            "type": "string"
          }
        }
      }
    }
  },
  "required": [
    "bio",
    "dislikes",
    "email",
    "emoticon",
    "likes",
    "links",
    "name",
    "photo",
    "title"
  ]
}

=== phl-code-club/website/src/organizers/graham.json
{
  "$schema": "../organizer.schema.json",
  "name": "Graham",
  "bio": "Graham is an all around computer nerd. What started out as a love of\nvideo games, moved into learning how to build computers and getting\ninterested in how they work, to learning to code. Now a software\nengineer, he aims to share his love of computing, especially the\nterminal, and continue learning from everyone he meets.",
  "likes": [
    "Terminals",
    "Ergonomic Keyboards",
    "Board Games",
    "My cat, Fritzy",
    "Data Sovereignty"
  ],
  "dislikes": [
    "GUI's",
    "Untyped Languages",
    "Mice (The HID, not the animal)",
    "Surveilance Capitalism"
  ],
  "title": "Chief Terminal Nerd",
  "photo": "./graham.webp",
  "emoticon": " ï‚åê‚ñ†·¥•‚ñ† î",
  "email": "graham@phlcode.club",
  "links": {
    "website": {
      "icon": "üîó",
      "url": "https://gvasquez.dev/?utm_source=code-club"
    }
  }
}

=== phl-code-club/website/src/organizers/taj.json
{
  "$schema": "../organizer.schema.json",
  "name": "Taj_Amani",
  "bio": "Taj is a dancing queen turned programming personality hire. He writes SQL by day and dances by night at the local YMCA. He hopes to bring a passion for life to PHL Code Club.",
  "likes": [
    "Dancing",
    "Britney Spears and Charli XCX",
    "Monarchy (ask about Norway)",
    "Cats",
    "Super Smash Bros"
  ],
  "dislikes": [
    "Sitting with feelings",
    "Grahams Keyboards",
    "When Fritzy doesn't want pets :("
  ],
  "title": "SVP Personality Hires",
  "photo": "../assets/Taj_Coffee.JPG",
  "emoticon": "(⸝⸝⸝• ω •⸝⸝⸝)♡",
  "email": "Taj@phlcode.club",
  "links": {}
}

=== phl-code-club/website/src/organizers/christina.json
{
  "$schema": "../organizer.schema.json",
  "name": "Christina",
  "bio": "Chris' first experience with coding came from breaking Tumblr themes until she was creating custom layouts. Fast-forward, working in IT and troubleshooting computer issues, her love for problem-solving grew. Now, she combines creativity and technical skills to build beautiful & functional UIs. She hopes to create an inclusive space to share her passion for coding.",
  "likes": [
    "Coding with friends",
    "Lifting Heavy Weights",
    "Board Games",
    "Thrifting",
    "crafts and starting DIY projects i'll never finish",
    "naps"
  ],
  "dislikes": [
    "loud noises"
  ],
  "title": "Chief Coding Diva",
  "photo": "./chris.jpg",
  "emoticon": "ʕ•ᴥ•ʔ",
  "email": "christina@phlcode.club",
  "links": {
    "website": {
      "icon": "🔗",
      "url": "https://cbtalia.com/"
    }
  }
}

=== phl-code-club/website/src/organizers/amaury.json
{
  "$schema": "../organizer.schema.json",
  "name": "Amaury",
  "bio": "Amaury grew up loving video games, often staying up late playing PokÃ©mon Silver into the night. That curiosity naturally evolved into a passion for computers. He loves seeing the creative ways code can take shape on a screen. Amaury believes that with code, you can create anything, and the only limits are those of the mind. He's dedicated to building spaces that foster inclusion, curiosity, and merriment.",
  "likes": [
    "Mini M&M's",
    "Chess",
    "MMA",
    "Bad Bunny",
    "Jalapeno Potato Chips"
  ],
  "dislikes": [
    "Certain Spicy Foods"
  ],
  "title": "L10 Crashout",
  "photo": "../assets/amaury.jpg",
  "emoticon": "Ê•à² á´¥à² Ê”",
  "email": "amaury@phlcode.club",
  "links": {
    "website": {
      "icon": "ðŸ”—",
      "url": "https://amaurycodes.onrender.com/"
    }
  }
}
